# frontend-gui deployment with OpenTelemetry Java Agent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-gui
  namespace: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-gui
  template:
    metadata:
      labels:
        app: frontend-gui
    spec:
      initContainers:
        - name: otel-agent-download
          image: curlimages/curl:8.2.1
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /otel-agent && \
              curl -sSL https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar \
              -o /otel-agent/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel-agent
      containers:
        - name: frontend-gui
          image: <username>/frontend-gui:v1
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -javaagent:/otel-agent/opentelemetry-javaagent.jar
                -Dotel.service.name=frontend-gui
                -Dotel.exporter.otlp.endpoint=http://tempo-distributor.monitoring.svc.cluster.local:4317
                -Dotel.exporter.otlp.protocol=grpc
                -Dotel.traces.exporter=otlp
                -Dotel.metrics.exporter=none
                -Dotel.logs.exporter=none
          volumeMounts:
            - name: otel-agent
              mountPath: /otel-agent
      volumes:
        - name: otel-agent
          emptyDir: {}
---
